config/routes.rb
Rails.application.routes.draw do

  resources :sports
    root 'welcome#home'

    get 'signup', to: 'users#new'
    post 'signup', to: 'users#create'

    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'

    delete 'logout', to: 'sessions#destroy'

    resources :users, except: [:index]
    # resources :sessions, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sport.rb
class Sport < ApplicationRecord
    has_many :rankings
    has_many :users, through: :rankings
end

app/models/user.rb
class User < ApplicationRecord
    has_many :rankings
    has_many :sports, through: :rankings

    has_secure_password

    validates :username, :email, :password, presence: true
    validates :username, :email, uniqueness: true
    validates :password, confirmation: true
    validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    # LOG IN
    def new
    end

    def create
        user = User.find_by(email: params[:user][:email])
        if user && user.authenticate(params[:user][:password])
            session[:user_id] = user.id
            flash[:success] = "You have successfully logged in"
            redirect_to user
        else
            flash.now[:danger] = "There was a problem with your login information."
            render :new
        end
    end

    def destroy
        session.clear
        # flash[:success] = "You have successfully logged out" 
        redirect_to root_path
    end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :find_user, only: [:show, :edit, :update, :destroy]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
    end

    def destroy
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    def find_user
        @user = User.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def home
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end


    def logged_in?
        !!current_user
    end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>RankUp</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <% if logged_in? %>
        <nav class='navbar'>
            <%= link_to 'Logout', '/logout', method: :delete %>
        <% else %>
            <%= link_to 'Login', login_path %>
            <%= link_to 'Signup', signup_path %>
        </nav>
        <% end %>

        <div class='container'>
            <%= yield %>
        </div>
  </body>
</html>

app/views/users/new.erb
<h1>Sign Up</h1>
<hr>
<% if flash[:message]%>
  <%= flash[:message] %>
<% end %>
<br>
<%= form_for :user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <%= f.label :password_confirmation, "Confirm your password" %>
    <%= f.password_field :password_confirmation %>
    <br>
    <%= f.submit "Sign Up" %>

<% end %>

app/views/users/show.erb
<h1><%= @user.username %>'s Profile</h1>
<hr>

app/views/welcome/home.erb
<h1>Welcome Home</h1>